# Generated by Django 3.2.16 on 2025-11-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('name2', models.CharField(max_length=256)),
                ('reg_num', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('email', models.EmailField(max_length=256)),
                ('avg_score', models.IntegerField()),
                ('city', models.CharField(max_length=256)),
                ('participation_in_olympiads', models.IntegerField()),
                ('avg_oge_score', models.IntegerField()),
                ('avg_score_of_exam', models.IntegerField()),
                ('is_on_main', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.profile')),
            ],
        ),
    ]
